### ISSUE TITLE
Unable to Compile on Windows 10 64 bit

### ISSUE THREAD

**Issue by agivney** [cfsamson/example-greenthreads#20] opened 2020-11-29 01:55 UTC
Thank you for the great work you have done this, I have found it very helpful from a learning perspective.

I did manage to get the code to compile in Linux, but I had no luck in Windows 10. I am using Nightly Rust version rustc 1.50.0-nightly. I did try both the debug and release modes of compilation.

I can confirm that I used the Windows Branch, the compilation error I am getting is:

error: could not compile `green_threads`

Caused by:
  process didn't exit successfully: `rustc --crate-name green_threads --edition=2018 src\main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ebe2d963b6e41045 --out-dir C:\Users\Arthur\Desktop\example-greenthreads\target\debug\deps -C incremental=C:\Users\Arthur\Desktop\example-greenthreads\target\debug\incremental -L dependency=C:\Users\Arthur\Desktop\example-greenthreads\target\debug\deps` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

I am guessing that is a segmentation fault. 

Is there something I am missing or doing incorrectly?

**Comment by cfsamson** [comment] 2020-12-03 15:26
Thanks for reporting this and great to hear that you've found it useful. 

I've been a bit busy but I'll try this myself as soon as possible. It looks like a segmentation fault, yes. There might have been some mistake that has sneaked in when I updated to the `llvm_asm` syntax since I didn't test that on every branch (it was a simple search/replace change, but these blocks are easy to mess up). Let me get back to you on this when I get time to test it myself on Windows.

Have you tried to compile and rund the code in the end of this chapter? https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/supporting-windows

They're supposed to be the same if I have managed to keep everything in sync as intended.

**Comment by cfsamson** [comment] 2020-12-03 15:42
Hmm. First I thought the changes made in #19 was the cuplrit, but then I tried to check out the first commit on that branch that I know for sure worked, but it fails with the same message on my computer as well. I'll need to look further in to this, since it worked on a previous version of Windows 10 there might have been some changes. For future reference, I'm on Windows 19041.630.

**Comment by cfsamson** [comment] 2020-12-03 22:38
Ok, so after thinking this through a bit there turns out to be a change in nightly causing this. The change seems to have occurred in the end of august 2020.

This works:
```
rustup override set nightly-2020-08-23
cargo run
```

This doesn't work:
```
rustup override set nightly-2020-08-24
cargo run
```


In other words, there is no change in Windows but a change in the Nightly compiler (which makes more sense). The change must have occurred between build `rustc 1.47.0-nightly (663d2f5cd 2020-08-22)` and `rustc 1.47.0-nightly (5180f3da5 2020-08-23)` and have been there ever since. 

I'll try to look more into this and the changes being merged these days to try to figure out what's going on.

**Comment by cfsamson** [comment] 2020-12-03 23:03
So I should start looking closer to the error message before debugging. This is actually the **compiler** having a segmentation fault and not the resulting binary. That's definitely not good.

**Comment by agivney** [comment] 2020-12-04 00:00
Thank you for following this up. I am interested to know what the problem is, I agree, it unusual. 

It is made harder when you cannot actually get a binary output (due to the compiler crashing) to check out what is happening, to look at the assembly itself.

**Comment by cfsamson** [comment] 2020-12-04 00:44
No problem. Yeah, I got a bit surprised by this myself. You can follow the issue here: https://github.com/rust-lang/rust/issues/79681

**Comment by cfsamson** [comment] 2020-12-05 23:30
OK, so it turns out that naked functions that uses formal parameters are unsupported. This is a hard error with a better description on the most recent nightly. Apparently, this caused a segfault in the compiler as you discovered until very recently.

This also applies to the linux version on the most recent nightly (try running the example in the playground and you get an error).

The fix is not extremely elegant. The one I landed on was to pass the arguments in registers using the calling convention for Linux and Windows like shown below. I call `switch` in the inline assembly here but I'm considering calling it like a normal function. I'm not sure what's clearest for the reader here. If you have any suggestions I'm open to them:

The function calling `switch` will look like this (for the cross platform version):
```rust
fn t_yield(&mut self) -> bool {
        let mut pos = self.current;
        while self.threads[pos].state != State::Ready {
            pos += 1;
            if pos == self.threads.len() {
                pos = 0;
            }
            if pos == self.current {
                return false;
            }
        }

        if self.threads[self.current].state != State::Available {
            self.threads[self.current].state = State::Ready;
        }

        self.threads[pos].state = State::Running;
        let old_pos = self.current;
        self.current = pos;

        unsafe {
            let old: *mut ThreadContext = &mut self.threads[old_pos].ctx;
            let new: *const ThreadContext = &self.threads[pos].ctx;

            if cfg!(not(target_os = "windows")) {
                llvm_asm!(
                    "mov $0, %rdi
                     mov $1, %rsi
                     call switch" ::"r"(old), "r"(new)
                );
            } else {
                llvm_asm!(
                    "mov $0, %rcx
                     mov $1, %rdx
                     call switch" ::"r"(old), "r"(new)
                );
            }
        }

        // preventing compiler optimizing our code away on windows. Will never be reached anyway.
        self.threads.len() > 0
    }
```

The `switch` function then accesses the arguments directly like shown here:

```
#[cfg(target_os = "windows")]
#[naked] // need to add this to call the function from inline assembly...
#[inline(never)]
#[no_mangle]
unsafe fn switch() {
    llvm_asm!(
        "
        movaps      %xmm6, 0x00(%rcx)
        movaps      %xmm7, 0x10(%rcx)
        movaps      %xmm8, 0x20(%rcx)
        movaps      %xmm9, 0x30(%rcx)
        movaps      %xmm10, 0x40(%rcx)
        movaps      %xmm11, 0x50(%rcx)
        movaps      %xmm12, 0x60(%rcx)
        movaps      %xmm13, 0x70(%rcx)
        movaps      %xmm14, 0x80(%rcx)
        movaps      %xmm15, 0x90(%rcx)
        mov         %rsp, 0xa0(%rcx)
        mov         %r15, 0xa8(%rcx)
        mov         %r14, 0xb0(%rcx)
        mov         %r13, 0xb8(%rcx)
        mov         %r12, 0xc0(%rcx)
        mov         %rbx, 0xc8(%rcx)
        mov         %rbp, 0xd0(%rcx)
        mov         %rdi, 0xd8(%rcx)
        mov         %rsi, 0xe0(%rcx)
        mov         %gs:0x08, %rax
        mov         %rax, 0xe8(%rcx)
        mov         %gs:0x10, %rax
        mov         %rax, 0xf0(%rcx)

        movaps      0x00(%rdx), %xmm6
        movaps      0x10(%rdx), %xmm7
        movaps      0x20(%rdx), %xmm8
        movaps      0x30(%rdx), %xmm9
        movaps      0x40(%rdx), %xmm10
        movaps      0x50(%rdx), %xmm11
        movaps      0x60(%rdx), %xmm12
        movaps      0x70(%rdx), %xmm13
        movaps      0x80(%rdx), %xmm14
        movaps      0x90(%rdx), %xmm15
        mov         0xa0(%rdx), %rsp
        mov         0xa8(%rdx), %r15
        mov         0xb0(%rdx), %r14
        mov         0xb8(%rdx), %r13
        mov         0xc0(%rdx), %r12
        mov         0xc8(%rdx), %rbx
        mov         0xd0(%rdx), %rbp
        mov         0xd8(%rdx), %rdi
        mov         0xe0(%rdx), %rsi
        mov         0xe8(%rdx), %rax
        mov         %rax, %gs:0x08
        mov         0xf0(%rdx), %rax
        mov         %rax, %gs:0x10

        ret
        "
    );
}
```

**Closed** 2020-12-05 23:42 UTC

**Comment by cfsamson** [comment] 2020-12-05 23:59
I decided to call `switch` outside the assembly to not add more complexity having to use the `no_mangle` attribute. I also added a paragraph explaining why we do this here: https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/simple-but-unsafe-green-thread-implementation#the-inconvenient-truth-about-naked-functions

**Comment by agivney** [comment] 2020-12-06 02:36
Cool, the master branch now compiles fine, even on Windows (however, I understand the potential for issues if the xmm* registers are not preserved. However, I needed to add 

use std::ptr;
to the Windows branch to get it to compile as I was getting the following error:
error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
 --> src\main.rs:262:13
 |
262 |  ptr::write(s_ptr.offset((size - 24) as isize) as *mut u64, guard as u64);
 |  ^^^ use of undeclared crate or module `ptr`

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
 --> src\main.rs:263:13
 |
263 |  ptr::write(s_ptr.offset((size - 32) as isize) as *mut u64, f as u64);
 |  ^^^ use of undeclared crate or module `ptr`

error: aborting due to 2 previous errors

Well done on updating the code. I think what you have done is valuable and I am looking forward now to playing with the code. Also, over the next few weeks I might have a crack at getting this to work on Arm 64, as I have a Raspberry Pi that I like to tinker with too. It has been a while since I used Assembler.

Thanks again for taking the time to do this.
Arthur.

    On Sunday, 6 December 2020, 10:59:45 am AEDT, Carl Fredrik Samson <notifications@github.com> wrote:  
 
 


I decided to call switch outside the assembly to not add more complexity having to use the no_mangle attribute. I also added a paragraph explaining why we do this here: https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/simple-but-unsafe-green-thread-implementation#the-inconvenient-truth-about-naked-functions

**Comment by cfsamson** [comment] 2020-12-06 17:42
Yeah. I noticed I hadent pushed the updates to the windows branch but it should be fixed now. Making it work in the rpi is a pretty cool project actually. Good luck!
